### ISSUE TITLE
I couldn't find the control_msg module in the compiled include folder.

### ISSUE THREAD

**Issue by G-Yong** [micro-ROS/micro_ros_platformio#104]
## Issue template

- Hardware description: 
ESP32

- RTOS: 
built-in

- Installation type: 
in the platformio.ini
`lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio`
![图片](https://github.com/micro-ROS/micro_ros_platformio/assets/21030893/172f825c-8b5d-4a47-b01f-96bcc4a4722e)

- Version or commit hash: 
humble

#### Steps to reproduce the issue

In vscode, I made the modifications as described earlier to platformio.ini. Then I pressed Ctrl+S to trigger automatic compilation by vscode. I obtained the following result, which is mostly fine, but it seems that the control_msg module is missing? I need this module because I need to communicate directly with the robot driver using MoveIt.
![图片](https://github.com/micro-ROS/micro_ros_platformio/assets/21030893/e94089f7-e0f5-4308-af89-2bed74881ab2)

#### Expected behavior
I thought this repository also had the control_msg module because I saw that the micro_ros_arduino repository has it, but it wasn't compiled in the end.
![图片](https://github.com/micro-ROS/micro_ros_platformio/assets/21030893/151c85e7-44f5-4128-8824-aea867b4fbb5)

**Comment by pablogs9** [comment]
If it is not available in the library, add it: https://github.com/micro-ROS/micro_ros_platformio#extra-packages
