### ISSUE TITLE
Same message is received continuously.

### ISSUE THREAD

**Issue by amalshaji4540** [micro-ROS/micro_ros_platformio#128]
## Issue template

- Hardware description:ESP32
Platform.io is used for building and flashing
ROS distro : ROS2 humble

I am working on a differential drive wheeled robot. teleop_twist_keyboard is used for sending the twist messages. I had created subscriber on topic cmd_vel using micro ros on ESP32. The messege is subscribed successfully. But the issue is when I send messages continuously at high frequency ( I press the key on teleop twist keyboard with out taking my finger ). The message received doesn't changes, same message is received at ESP32 if I send another message from telop twist keyboard. 

This issue occur only when I send message at a high rate. Otherwise everything works as expected.

Is there any ways to get last sent message.

**Comment by pablogs9** [comment]
Are you subscribing in best effort?

**Comment by amalshaji4540** [comment]
No, I am subscribing in default 

RCCHECK(rclc_subscription_init_default(
    &subscriber,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(geometry_msgs, msg, Twist),
    "cmd_vel"));

**Comment by pablogs9** [comment]
It is probably a good idea to move to best effort if you are publishing on a topic with a high rate.

**Comment by amalshaji4540** [comment]
Okey, thank you. I will try it out.

**Comment by amalshaji4540** [comment]
@pablogs9  Thank you for the advice. Best effort works really well.

**Comment by pablogs9** [comment]
Good to hear that!
