### ISSUE TITLE
Builder does not care whether extra packages are cloned correctly

### ISSUE THREAD

**Issue by bjsowa** [micro-ROS/micro_ros_platformio#14]
When `extra_packages.yaml` contains incorrect `url` or `version` and cloning the package does not succeed, the builder will still say that it downloaded the package and continue building the library.

**Comment by Acuadros95** [comment]
Build error checks added on https://github.com/micro-ROS/micro_ros_platformio/pull/15

**Comment by bjsowa** [comment]
Wow, that was fast. I checked it and it seems to fix this issue.
