### ISSUE TITLE
lib_deps =     https://github.com/micro-ROS/micro_ros_platformio is not working

### ISSUE THREAD

**Issue by flux0-0** [micro-ROS/micro_ros_platformio#146]
## Issue template

- Hardware descriptionUbuntu 22.04.4 LTS -->
- Version or commit hash:  humble  -->

#### Steps to reproduce the issue
if I save my platform.ino 
[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = espidf
lib_deps =
    https://github.com/micro-ROS/micro_ros_platformio

i have " 
Building micro-ROS library
Build mcu micro-ROS environment failed: 
--- stderr: rcutils
In function 'rcutils_strndup',
    inlined from 'rcutils_strdup' at /home/bao/Documents/PlatformIO/Projects/micro_bot/.pio/libdeps/esp32doit-devkit-v1/micro_ros_platformio/build/mcu/src/rcutils/src/strdup.c:35:10:
/home/bao/Documents/PlatformIO/Projects/micro_bot/.pio/libdeps/esp32doit-devkit-v1/micro_ros_platformio/build/mcu/src/rcutils/src/strdup.c:46:14: error: 'memchr' specified bound 4294967295 exceeds maximum object size 2147483647 [-Werror=stringop-overread]
   46 |   char * p = memchr(str, '\0', max_length);
      |              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
gmake[2]: *** [CMakeFiles/rcutils.dir/build.make:348: CMakeFiles/rcutils.dir/src/strdup.c.obj] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:192: CMakeFiles/rcutils.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< rcutils [1.10s, exited with code 2]
 "

**Comment by hippo5329** [comment]
The micro-ros-platformio uses arduino framework.

framework=arduino
