### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by v-mifass** [micro-ROS/micro_ros_platformio#20]
## Issue template

- Hardware description: Teensy 4.1
- RTOS: micro-ROS arduino

- Version or commit hash: main

#### Steps to reproduce the issue
platform.ini file:
```ini
[env:teensy41]
platform = teensy
board = teensy41
board_microros_distro = galactic
board_microros_transport = serial
framework = arduino
lib_deps = 
	https://github.com/micro-ROS/micro_ros_platformio
```
#### Expected behavior
compile

#### Actual behavior
Error
```bash
Requirement already satisfied: markupsafe==2.0.1 in c:\users\v-mifass\.platformio\penv\lib\site-packages (2.0.1)
Configuring teensy41 with transport serial
Downloading micro-ROS dev dependencies
ament_cmake clone failed: 
fatal: Too many arguments.
```

**Comment by Acuadros95** [comment]
Could not replicate this. What is your git version? 
`git --version`

**Comment by pablogs9** [comment]
Should we check if `git` executable is in the path before running it? @Acuadros95

**Comment by pablogs9** [comment]
Also, because of the `c:\` I guess that @v-mifass is running Windows. Maybe we should explore the possibility of porting this to Windows.

**Comment by v-mifass** [comment]
yes running platformio on windows.  Git version 2.35.1.windows.2

**Comment by v-mifass** [comment]
So compiling in Linux does work.  This can be closed unless a version to compile on platformio on windows is an 'issue'

**Comment by Acuadros95** [comment]
Closing, support for windows is not currently under development due to colcon cross compilation issues on windows.
