### ISSUE TITLE
Intellisense in VS Code not working with micro_ros_platformio

### ISSUE THREAD

**Issue by DaniGarciaLopez** [micro-ROS/micro_ros_platformio#32]
First of all I want to thank you guys to support PlatformIO, we really appreciate it! 

Previously we were working in PlatformIO with micro_ros_arduino. I ported the project to this new repo and everything compiles fine except that Intellisense in VS Code is not recognizing `#include <micro_ros_platformio.h>` anymore, so syntax highlight in micro-ROS is not working.

PlatformIO correctly adds `micro_ros_platformio` in `c_cpp_properties.json`, I also tried to rebuild Intellisense index with no luck. Any help is welcome. Thanks!

- Hardware description: Teensy 3.2
- Version or commit hash: Ubuntu 20.04 galactic, main branch last commit, platformio 6.0.1, vs code 1.67.2, c/c++ extension 1.9.8

#### Steps to reproduce the issue
- Clone this repository
- Go to `/ci` folder
- Open VS Code
- Check that PlatformIO and C/C++ extensions are installed and active
- Open PlatformIO terminal:
```
pio lib install
pio run
pio run --target upload
```
#### Expected behavior
Intellisense should work, `#include <micro_ros_platformio.h>` is found and code highlight works

#### Actual behavior
Intellisense is not working, `#include <micro_ros_platformio.h>` not found. 
Error: `#include errors detected. Please update your includePath. Squiggles are disabled for this translation unit`

**Comment by Genozen** [comment]
I have similar issue, but mine builds regardless...
Have you had any success getting the board running?

**Comment by DaniGarciaLopez** [comment]
Hi @Genozen. Mine also builds fine, just Intellisense is not working. I haven't found a solution, if you do, please let me know!

**Comment by Acuadros95** [comment]
Should be fixed with https://github.com/micro-ROS/micro_ros_platformio/pull/44. Please check it out!

**Comment by DaniGarciaLopez** [comment]
I've just tested and it works fine! Thanks @bjsowa @Acuadros95
