### ISSUE TITLE
adding native_ethernet to portenta H7

### ISSUE THREAD

**Issue by b0hne** [micro-ROS/micro_ros_platformio#41]
Hi,
I used this repo on a Portenta H7, in oder to use native_ethernet i had to replace:
platform_code/arduino/native_ethernet/micro_ros_transport.cpp
#5 #include <NativeEthernetUdp.h> with <EthernetUdp.h>
and
platform_code/arduino/native_ethernet/micro_ros_transport.h
#1 #include <NativeEthernet.h> with #include <EthernetUdp.h>

I would create a pull request, but i don't know how to embed it into the existing system.

**Comment by pablogs9** [comment]
Yes please, can you create a PR with those changes?

**Comment by b0hne** [comment]
https://github.com/micro-ROS/micro_ros_platformio/pull/49

**Comment by pablogs9** [comment]
Moving to #49
