### ISSUE TITLE
Adding custom ROS messages for microROS platformIO

### ISSUE THREAD

**Issue by Genozen** [micro-ROS/micro_ros_platformio#42]
I'm trying to follow the tutorial from microROS custom messages: [https://micro.ros.org/docs/tutorials/advanced/create_new_type/]

Is there a similar way to do this custom messages in the platformIO version?

**Comment by pablogs9** [comment]
Just copy your packages to the folder mentioned here: https://github.com/micro-ROS/micro_ros_platformio#extra-packages

**Comment by ssaattww** [comment]
is it means  "myProject/.pio/libdeps/board_name/micro_ros_platformio/extra_packages/my_packages"?

**Comment by pablogs9** [comment]
That's it

**Comment by ssaattww** [comment]
No need to add parent directry to libdeps like this, right? https://github.com/micro-ROS/micro_ros_platformio/blob/c9c410c9c7b93cca685cd19786978b0589f23ad9/ci/platformio.ini#L9

**Comment by pablogs9** [comment]
I don't think so. Do we have any examples of custom packages for platformio @Acuadros95 ?

**Comment by Acuadros95** [comment]
You can check out our CI, which includes a project example with `extra_packages`: [link](https://github.com/micro-ROS/micro_ros_platformio/tree/main/ci).

> is it means "myProject/.pio/libdeps/board_name/micro_ros_platformio/extra_packages/my_packages"?

The folder should be at the same level of the `platformio.ini` file: `myProject/extra_packages/my_packages`, sorry for the confusion.

**Comment by ssaattww** [comment]
solved. Thank you for your support.

**Comment by Genozen** [comment]
@ssaattww  did you get this error?
```
  // // create publisher2
  RCCHECK(rclc_publisher_init_default(
    &publisher2,
    &node,
    ROSIDL_GET_MSG_TYPE_SUPPORT(my_custom_message, custom_msg, MyCustomMessage),
    "micro_ros_my_custom_publisher"));
```
![image](https://user-images.githubusercontent.com/74474611/180862674-38c6a3a2-8f6a-4542-8b4f-eb0ca61b9614.png)

**Comment by ssaattww** [comment]
no, Once I success to built, all is done.
