### ISSUE TITLE
multiple definition of clock_gettime'

### ISSUE THREAD

**Issue by samuk** [micro-ROS/micro_ros_platformio#47]
## Issue template

- Hardware description: ESP32 feather
- RTOS: Arduino/Platformio
- Installation type: https://github.com/rosmo-robot/linorobot2_hardware
- Version or commit hash: Humble

#### Steps to reproduce the issue
https://github.com/rosmo-robot/linorobot2_hardware#1-motor-check

#### Expected behavior

Software compiles without error

#### Actual behavior

Linking to ticket I opened on Linorobot to avoid duplicaton: https://github.com/linorobot/linorobot2_hardware/issues/19

**Comment by pablogs9** [comment]
Anwered [here](https://github.com/linorobot/linorobot2_hardware/issues/19)
