### ISSUE TITLE
Wifi support - Status unclear

### ISSUE THREAD

**Issue by samuk** [micro-ROS/micro_ros_platformio#52]
## Issue template

- Hardware description: ESP32

#### Steps to reproduce the issue
Check readme https://github.com/micro-ROS/micro_ros_platformio#transport-configuration
Check code https://github.com/micro-ROS/micro_ros_platformio/blob/main/platform_code/arduino/wifi/micro_ros_transport.cpp

#### Expected behavior

ROS2 computer can communicate with ESP32 device using wifi. This is documented in the readme.

#### Actual behavior
Wifi support is undocumented

#### Additional information
If it's not yet implemented I might try this https://github.com/NITKK-ROS-Team/micro_ros_arduino_simpler#readme as it supports wifi I think.

**Comment by Acuadros95** [comment]
Could you elaborate on this issue?

Did you try to use the esp32 wifi transport? Currently it builds OK on our CI: [detail](https://github.com/micro-ROS/micro_ros_platformio/blob/main/ci/platformio.ini#L151).
