### ISSUE TITLE
MicroROS ESP32 Over-the-air upload

### ISSUE THREAD

**Issue by Genozen** [micro-ROS/micro_ros_platformio#56]
Just wondering if the microROS platformIO version supports over the air upload like this one: `https://randomnerdtutorials.com/esp32-over-the-air-ota-programming/#:~:text=Upload%20a%20new%20sketch%20over%2Dthe%2Dair%20to%20the%20ESP32,code%20should%20be%20successfully%20uploaded.`

or anyway to upload the microROS to multiple ESP32 at once?

**Comment by Acuadros95** [comment]
You should be able to upload the platformIO generated bin file just as the one from Arduino:

```bash
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [==        ]  16.6% (used 86912 bytes from 523624 bytes)
Flash: [====      ]  38.7% (used 304080 bytes from 786432 bytes)
Building .pio/build/portenta_h7_m7_galactic/firmware.bin
```

Check your platformIO build log and try with the generated binary, `.pio/build/portenta_h7_m7_galactic/firmware.bin` in this case.

Closing as not related to micro-ROS.
