### ISSUE TITLE
increasing subscribers and publishers on portenta H7

### ISSUE THREAD

**Issue by b0hne** [micro-ROS/micro_ros_platformio#58]
Hi, i want to use 12 publishers/topics on the Portenta H7,
I tried changing: ./Projects/project_name/.pio/libdeps/portenta_h7_m7/micro_ros_platformio/libmicroros/include/rmw_microxrcedds_c/config.h
#define RMW_UXRCE_MAX_PUBLISHERS 10, changed to 12
but the topic i use for testing just stops working when the elevenths publisher is instantiated. 
is there another variable? I dont think the portenta really minds having more than 10 topics...

**Comment by Acuadros95** [comment]
Check the [Other configuration](https://github.com/micro-ROS/micro_ros_platformio#other-configuration) Readme section for details on how to add your own configuration on a `.meta` file.
