### ISSUE TITLE
highlight differences to micro_ros_arduino

### ISSUE THREAD

**Issue by patrickwasp** [micro-ROS/micro_ros_platformio#83]
It's not clear to me what the differences are between this project and [micro_ros_arduino](https://github.com/micro-ROS/micro_ros_arduino) and when I would use one versus the other. I think adding a note highlighting the differences would help others looking at the two projects. 

For example 

```
[env:seeed_xiao]
platform = atmelsam
board = seeed_xiao
framework = arduino

lib_deps =
    https://github.com/micro-ROS/micro_ros_arduino#v2.0.5-humble

build_flags =
    -L ./.pio/libdeps/seeed_xiao/micro_ros_arduino/src/cortex-m0plus/
    -l microros
    -D micro_ros_xiao.json
```

works fine in platformIO. When and why would I use this project instead?

**Comment by pablogs9** [comment]
![image](https://user-images.githubusercontent.com/7647884/202980503-7385a427-a3f5-40f7-a3c6-7dfcaeb15d7f.png)

As stated, the micro_ros_arduino is intended to be used with Arduino IDE or Arduino CLI.

micro_ros_platformio is intended to be used with Platform.IO, which can or cannot be related to Arduino.

**Comment by patrickwasp** [comment]
Okay so just to check if I understand correctly. The practical difference between the two projects It's only a matter of IDE preference. Originally the micro_ros_arduino project provided support for platform io, but now PIO support has moved to this project.

https://github.com/micro-ROS/micro_ros_arduino#platformio
> PlatformIO
> PlatformIO support for this repository has been deprecated in favor of its own build system: [micro_ros_platformio](https://github.com/micro-ROS/micro_ros_platformio)

And for now, `micro_ros_platformio` only supports the Arduino framework running on bare metal with no RTOS, but in the future, it could potentially support NuttX, FreeRTOS, and Zephyr.
